version: '3.3'
services:
  MYSQL:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    container_name: MYSQL_DATABASE
    environment:
      MYSQL_DATABASE: 'awp_u1667086'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'akazkouzeh'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'nPrCpYX3eNpxkD7Y'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'nPrCpYX3eNpxkD7Y'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
  Web-Server:
    image: awp:laravel
    restart: always
    ports:
      - "80:80"
      - "8000:8000"
    links:
      - MYSQL
    volumes:
      - ./:/var/www/html
      - "./php.ini:/usr/local/etc/php/php.ini"
    command: sh /var/www/html/start.sh
